package edu.wisc.cs.will.Utils;

/*
 * @author twalker
 */
public enum MessageType {
    STRING_HANDLER_CREATION,
    STRING_HANDLER_VARIABLE_INDICATOR,
    STRING_HANDLER_PREDICATE_COSTS,

    ISA_HANDLER_TYPE_INFERENCE,

    PARSER_VERBOSE_LIBRARY_LOADING,

    ILP_THESHOLDING_VERBOSE,

    ILP_OUTERLOOP,
    ILP_INNERLOOP
}
